### ISSUE TITLE
Fatal error with Xcode 14 and iOS 16

### ISSUE THREAD

**Issue by horpot** [envoy/Embassy#101] opened 2022-09-08 12:27 UTC
Hello,
When running my project with Xcode 14 RC and iOS 16 RC(on an iPhone X) I get a fatal error:
```
Swift/arm64-apple-ios.swiftinterface:23320: Fatal error
In file TCPSocket line 117
```
Could anyone help?
Thanks

**Comment by D3icidal** [comment] 2022-09-15 22:14
Same issue on xcode 14 public version, with any version of iOS (tried 16, 15.5, 14.5)

**Comment by NikeshGajavelly** [comment] 2022-09-19 22:24
Any fix for this issue please?

**Comment by samrayner** [comment] 2022-09-20 10:04
https://github.com/envoy/Embassy/pull/100

**Comment by willywagtail** [comment] 2022-09-20 12:00
Any progress on merging this MR?

**Comment by willywagtail** [comment] 2022-09-20 12:02
> #100

Any progress on merging this MR?

**Comment by jaysirju** [comment] 2022-09-20 12:48
@Goos Are you able to Merge [this](https://github.com/envoy/Embassy/pull/100) so we can continue using this library?  Thanks!

**Comment by ekscrypto** [comment] 2022-09-20 19:38
+1 please deploy the fix as soon as possible

**Comment by beckychristensen** [comment] 2022-10-12 16:38
This should be fixed in https://github.com/envoy/Embassy/releases/tag/v4.1.4

**Closed by beckychristensen** 2022-10-12 16:38 UTC

**Comment by ngtrungt** [comment] 2022-10-28 02:47
Please deploy to Pods.
Pods still in ver 4.1.1

**Comment by beckychristensen** [comment] 2022-10-29 16:34
@ngtrungt please check again, it was deployed to Pods when I closed this issue. https://cocoapods.org/pods/Embassy shows 4.1.4

**Comment by ngtrungt** [comment] 2022-10-31 01:29
> @ngtrungt please check again, it was deployed to Pods when I closed this issue. https://cocoapods.org/pods/Embassy shows 4.1.4

Pod file: pod 'Embassy', '~> 4.1'
Results:
Analyzing dependencies
Downloading dependencies
Installing Embassy (4.1.1)
Generating Pods project
Integrating client projects
Pod installation complete!

Pod file: pod 'Embassy', '~> 4.1.4'
Result:
Analyzing dependencies
[!] CocoaPods could not find compatible versions for pod "Embassy":
  In Podfile:
    Embassy (~> 4.1.4)

Please help to check.

Thanks

**Comment by beckychristensen** [comment] 2022-10-31 18:09
@ngtrungt I'm sorry, I cannot reproduce your issue. I have been using `4.1.4` of the Embassy pod in our project the past few weeks and it is working correctly. 

Podfile contains `pod 'Embassy', '~> 4.1.4'`

command line:
```
pod install
Analyzing dependencies
Downloading dependencies
Installing Embassy 4.1.4
Generating Pods project
Integrating client project
Pod installation complete! There are 33 dependencies from the Podfile and 35 total pods installed.
```

- Do you perhaps have another Pod dependency that is explicitly requesting a lower version of Embassy? If you remove Embassy from your podfile and run `pod install`, do you still see Embassy in your podfile.lock? This could mean another of your dependencies is also using it, and they might be causing the version issue you are seeing. 
- What happens if you leave your podfile with `pod 'Embassy', '~> 4.1'` and run `pod update Embassy`?

**Comment by murraygoodwin** [comment] 2022-10-31 20:43
I don’t know if it’s relevant but we were previously using EmbassyAmbassador and I had this same issue where I couldn’t get the latest version. When I changed the pod to Embassy or Envoy(?) I forget… it worked.

Kind regards,
Murray Goodwin

**Comment by ngtrungt** [comment] 2022-11-01 01:19
> * pod update Embassy

I appreciate your support. It worked.
